package Model.enums;

public enum Paises {
    INDIA, CHILE, COLOMBIA,AUSTRALIA,ARGENTINA,PERU,USA,CANADA;
    //COLOMBIA,INDIA,ARGENTINA,AUSTRALIA,CHILE,VENEZUELA,PERU,USA,CANADA,URUGUAY,ECUADOR,BOLIVIA,PARAGUAY,JAPON,CHINA,SURCOREA,RUSIA,ESPAÑA;
}
